config/routes.rb
Tablero::Application.routes.draw do

  resources :teams do
  resources :members
  end

   resources :questions do
  resources :answers
  end

  resources :users

  resources :results

  #resources :answers

  #resources :questions

  #resources :members

  resources :categories

  resources :rols

  resources :awards

  resources :winners

get "pages/index"
resources :teams
resources :pages
root :to => 'pages#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  attr_accessible :answer, :letter
end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :name, :order
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :team
  attr_accessible :name, :team_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :answer
  attr_accessible :description, :letter, :score
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :answer
  belongs_to :question
  belongs_to :team
  attr_accessible :ok
end

app/models/rol.rb
class Rol < ActiveRecord::Base
  attr_accessible :name
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :members
  attr_accessible :name, :score
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :rol
  attr_accessible :email, :name, :pasword
end

app/models/winner.rb
class Winner < ActiveRecord::Base
  attr_accessible :dategame, :namemember, :nameteam, :score
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_filter :find_question_answers

  def index
    @answers = @question.answer.all
    respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @answers }
    end
  end

  def show
     
  end

  def new
      @answer =  Answer.new
  end

  def edit
     
  end

  def create
      @answer = @question.answer.build(params[:answer])
      render :action => :new unless @answer.save
  end

  def update
    render :action => :edit unless @answer.update_attributes(params[:answer])
  end

  def destroy
    @answer.destroy
  end

  private

  def find_question_answers
     @question = Question.find(params[:question_id])
     @answer = Answer.find(params[:id]) if params[:id]
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_base_errors resource
return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
html = <<-HTML
<div class="alert alert-error alert-block">
<button type="button" class="close" data-dismiss="alert">&#215;</button>
#{messages}
</div>
HTML
html.html_safe
end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/answers/_answer.html.erb
<tr id=<%= "answer_#{answer.id}" %>>

  <td><%= answer.answer %></td>
  <td>
    <%= link_to 'Mostrar', question_answer_path(@question, answer), :remote => true, :class => 'btn btn-mini' %>
    <%= link_to 'Editar', edit_question_answer_path(@question, answer), :remote => true,
        :class => 'btn btn-mini' %>
    <%= link_to 'Eliminar', question_answer_path(@question, answer), 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/answers/_form.html.erb
<%= simple_form_for([@question,  @answer], :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @answer %>

  <%= f.input :answer, :label => "responder",  :required => true %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', question_answers_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/answers/_show.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='answer'>
  <p><%= @answer.id %></p>
  <p><%= @answer.answer %></p>
</div>

app/views/answers/create.js.erb
$('table tbody').append("<%= escape_javascript(render @answer) %>")
$.lazybox.close()

app/views/answers/destroy.js.erb
$("table tr#answer_<%= @answer.id %>").remove();

app/views/answers/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/answers/index.html.erb
<%- model_class = Answer-%>
<div class="page-header">
  <h1>Listado de Respuestas de: <%= @question.description %></h1>
</div>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>id</th>
      <th>responder</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
     <%= render @answers %>
  </tbody>
  <tfoot>
    <tr>
     
      <td><%= link_to 'Nuevo Respuestas', new_question_answer_path, :remote => true  %> </td>
      <td><%= link_to 'Atras', questions_path %></td>
    </tr>
  </tfoot>
</table>

app/views/answers/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/answers/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/answers/update.js.erb
$('tr#answer_<%= @answer.id %>').replaceWith("<%= escape_javascript(render @answer) %>")
$.lazybox.close()