config/routes.rb
Tablero::Application.routes.draw do

  resources :teams do
  resources :members
  end

   resources :questions do
  resources :answers
  end

  resources :users

  resources :results

  #resources :answers

  #resources :questions

  #resources :members

  resources :categories

  resources :rols

  resources :awards

  resources :winners

get "pages/index"
resources :teams
resources :pages
root :to => 'pages#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  attr_accessible :answer, :letter
end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :name, :order
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :team
  attr_accessible :name, :team_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :answer
  attr_accessible :description, :letter, :score
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :answer
  belongs_to :question
  belongs_to :team
  attr_accessible :ok
end

app/models/rol.rb
class Rol < ActiveRecord::Base
  attr_accessible :name
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :members
  attr_accessible :name, :score
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :rol
  attr_accessible :email, :name, :pasword
end

app/models/winner.rb
class Winner < ActiveRecord::Base
  attr_accessible :dategame, :namemember, :nameteam, :score
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController

  def index
    @awards = Award.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @award }
    end
  end

  def show
      @award = Award.find(params[:id])
  end

  def new
      @award = Award.new
  end

  def edit
      @award = Award.find(params[:id])
  end

  def create
      @award = Award.new(params[:award])
      render :action => :new unless @award.save
  end

  def update
      @award = Award.find(params[:id])
      render :action => :edit unless @award.update_attributes(params[:award])
  end

  def destroy
      @award = Award.find(params[:id])
      @award.destroy
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_base_errors resource
return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
html = <<-HTML
<div class="alert alert-error alert-block">
<button type="button" class="close" data-dismiss="alert">&#215;</button>
#{messages}
</div>
HTML
html.html_safe
end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/awards/_award.html.erb
<tr id=<%= "award_#{award.id}" %>>
  <td><%= link_to award.id, edit_award_path(award), :remote => true %></td>
  <td><%= award.name %></td>
  <td>
    <%= link_to 'Mostrar', award, :remote => true, :class => 'btn btn-mini' %>
    <%= link_to 'Editar', edit_award_path(award), :remote => true,
        :class => 'btn btn-mini' %>
    <%= link_to 'Eliminar', award, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/awards/_form.html.erb
<%= simple_form_for(@award, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @award %>

  <%= f.input :name, :label => "Nombre",  :required => true %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', awards_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/awards/_show.html.erb
<%- model_class = Award -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='team'>
  <p>id: <%= @award.id %></p>
  <p>descripcion: <%= @award.name %></p>
</div>

app/views/awards/create.js.erb
$('table tbody').append("<%= escape_javascript(render @award) %>")
$.lazybox.close()

app/views/awards/destroy.js.erb
$("table tr#award_<%= @award.id %>").remove();

app/views/awards/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/awards/index.html.erb
<%- model_class = Award -%>
<div class="page-header">
  <h1>Premios</h1>
</div>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>id</th>
      <th>Nombre</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
     <%= render @awards %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to 'Nuevo Premios', new_award_path, :remote => true %></td>
    </tr>
  </tfoot>
</table>

app/views/awards/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/awards/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/awards/update.js.erb
$('tr#award_<%= @award.id %>').replaceWith("<%= escape_javascript(render @award) %>")
$.lazybox.close()