config/routes.rb
Tablero::Application.routes.draw do

  resources :teams do
  resources :members
  end

   resources :questions do
  resources :answers
  end

  resources :users

  resources :results

  #resources :answers

  #resources :questions

  #resources :members

  resources :categories

  resources :rols

  resources :awards

  resources :winners

get "pages/index"
resources :teams
resources :pages
root :to => 'pages#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  attr_accessible :answer, :letter
end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :name, :order
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :team
  attr_accessible :name, :team_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :answer
  attr_accessible :description, :letter, :score
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :answer
  belongs_to :question
  belongs_to :team
  attr_accessible :ok
end

app/models/rol.rb
class Rol < ActiveRecord::Base
  attr_accessible :name
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :members
  attr_accessible :name, :score
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :rol
  attr_accessible :email, :name, :pasword
end

app/models/winner.rb
class Winner < ActiveRecord::Base
  attr_accessible :dategame, :namemember, :nameteam, :score
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_filter :find_team_members

  def index
    @members = @team.members.all
    respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @members }
    end
  end

  def show
     
  end

  def new
      @member =  Member.new
  end

  def edit
     
  end

  def create
      @member = @team.members.build(params[:member])
      render :action => :new unless @member.save
  end

  def update
    render :action => :edit unless @member.update_attributes(params[:member])
  end

  def destroy
    @member.destroy
  end

  private

  def find_team_members
     @team = Team.find(params[:team_id])
     @member = Member.find(params[:id]) if params[:id]
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def display_base_errors resource
return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
html = <<-HTML
<div class="alert alert-error alert-block">
<button type="button" class="close" data-dismiss="alert">&#215;</button>
#{messages}
</div>
HTML
html.html_safe
end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/members_helper.rb
module MembersHelper
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for([@team, @member], :html => { :class => 'form-horizontal' },
 :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @member %>

  <%= f.input :name, :label => "Nombre",  :required => true %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', team_members_path, :class => 'btn btn-small' %>
  </div>
<% end %>



	

app/views/members/_member.html.erb
<tr id=<%= "member_#{member.id}" %>>

  <td><%= member.name %></td>
  <td>
    <%= link_to 'Mostrar', team_member_path(@team, member), :remote => true, :class => 'btn btn-mini' %>
    <%= link_to 'Editar', edit_team_member_path(@team, member), :remote => true,
        :class => 'btn btn-mini' %>
    <%= link_to 'Eliminar', team_member_path(@team, member), 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/members/_show.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='team'>
  <p>id: <%= @member.id %></p>
  <p>descripcion: <%= @member.name %></p>
</div>

app/views/members/create.js.erb
$('table tbody').append("<%= escape_javascript(render @member) %>")
$.lazybox.close()

app/views/members/destroy.js.erb
$("table tr#member_<%= @member.id %>").remove();

app/views/members/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/members/index.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1>Listado de members de: <%= @team.name %></h1>
</div>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>nombre</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
     <%= render @members %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to 'Nuevo members', new_team_member_path, :remote => true  %> </td>
      <td><%= link_to 'Atras', teams_path %></td>
    </tr>
  </tfoot>
</table>

app/views/members/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/members/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/members/update.js.erb
$('tr#member_<%= @member.id %>').replaceWith("<%= escape_javascript(render @member) %>")
$.lazybox.close()